## CmpE 545 - Reinforcement Learning
Gönül AYCI - 2016800003

In [1]:
import numpy as np

## Initialization

In [2]:
gamma = 0.9
epsilon = 1
epsilon_update = .98

nEpisodes = 35

nRows = 8
nCols = 8

nDirections = 4
actions = ['N', 'E', 'S', 'W']

goal = [6,5] # goal state
r[6][5] = 100

r = np.zeros((nRows, nCols))
Q = np.zeros((nRows, nCols, nDirections))

# eta is the history matrix
number = np.ones((nRows, nCols, nDirections))
eta = np.ones((nRows, nCols, nDirections))
#eta = 0.2

## Deterministic Case

In [3]:
# this function helps to move to the next state
def state_moves(s):
    moves = [[0,1], [1,0], [0, -1], [-1, 0]]
    moves

    if(s[0] == 0):
        moves[3] = [0,0]
    if(s[0] == nCols-1):
        moves[1] = [0,0]
    if(s[1] == 0):
        moves[2] = [0,0]
    if(s[1] == nRows-1):
        moves[0] = [0,0]
    return moves

In [4]:
for e in range(nEpisodes):
    # initialize the start state
    s = [1,1]
    
    while((s[0] != goal[0]) or (s[1] != goal[1])):
        # apply epsilon-greedy to take an action a
        epsilon_rand = np.random.rand()
        # best action
        if(epsilon_rand > epsilon):
            a = np.argmax(Q[s[0]][s[1]][:])
        # uniform
        else:
            a = np.random.randint(nDirections)
        
        # initialize a next state
        moves = state_moves(s)
        s_next = [sum(x) for x in zip(s, moves[a])]

        # apply an update rule
        dQ = r[s_next[0]][s_next[1]] + gamma * np.max(Q[s_next[0]][s_next[1]])
        Q[s[0]][s[1]][a] = dQ
        
        s = s_next
        
    epsilon *= epsilon_update

## The best actions

In [5]:
np.max(np.around(Q, decimals=1), axis = 2)

array([[  34.9,   38.7,   43. ,   47.8,   43. ,   47.8,   53.1,   47.8],
       [  38.7,   43. ,   47.8,   53.1,   59. ,   65.6,   59. ,   53.1],
       [  43. ,   47.8,   53.1,   59. ,   65.6,   72.9,   65.6,   59. ],
       [  47.8,   53.1,   59. ,   65.6,   72.9,   81. ,   72.9,   65.6],
       [  53.1,   59. ,   65.6,   72.9,   81. ,   90. ,   81. ,   72.9],
       [  59. ,   65.6,   72.9,   81. ,   90. ,  100. ,   90. ,   81. ],
       [  53.1,   72.9,   81. ,   90. ,  100. ,    0. ,  100. ,   90. ],
       [   0. ,   65.6,   72.9,   81. ,   90. ,  100. ,   90. ,   81. ]])

## All actions

In [6]:
np.around(Q, decimals=1)

array([[[  34.9,    0. ,    0. ,    0. ],
        [  38.7,   38.7,    0. ,    0. ],
        [  43. ,   43. ,   34.9,    0. ],
        [  38.7,   47.8,   38.7,   43. ],
        [  43. ,    0. ,   43. ,    0. ],
        [  47.8,    0. ,    0. ,   43. ],
        [  43. ,   53.1,   43. ,   47.8],
        [   0. ,   47.8,   38.7,   43. ]],

       [[  38.7,   38.7,   34.9,    0. ],
        [  43. ,   43. ,   34.9,   34.9],
        [  47.8,   47.8,   38.7,   38.7],
        [  53.1,   53.1,   43. ,   43. ],
        [  59. ,    0. ,    0. ,    0. ],
        [  53.1,   65.6,    0. ,    0. ],
        [  47.8,   59. ,    0. ,   47.8],
        [  47.8,   53.1,   53.1,   43. ]],

       [[   0. ,   43. ,   38.7,    0. ],
        [  47.8,   47.8,   38.7,    0. ],
        [  53.1,   53.1,   43. ,   43. ],
        [  59. ,   59. ,   47.8,   47.8],
        [  65.6,   65.6,   53.1,   43. ],
        [  59. ,   72.9,   59. ,   59. ],
        [  53.1,   65.6,   65.6,   53.1],
        [  53.1,   59. ,   59.

## Nondeterministic Case (SARSA)

In [11]:
prime_rand = np.random.rand()
prime_rand2 = np.random.rand()

def action_next(a):
    if(prime_rand > .5):
        if(prime_rand2 > .5):
            a_prime = ((a-2) % nDirections)
        else:
            a_prime = (a % nDirections)
    return a_prime

In [12]:
for e in range(nEpisodes):
    s = [1,1]
    
    while((s[0] != goal[0]) or (s[1] != goal[1])):
        epsilon_rand = np.random.rand()
        # best action
        if(epsilon_rand > epsilon):
            a = np.argmax(Q[s[0]][s[1]][:])
        # uniform
        else:
            a = np.random.randint(nDirections)
            
        a_next = action_next(a)
        moves = state_moves(s)
        s_next = [sum(x) for x in zip(s, moves[a_next])]
        dQ = eta[s[0]][s[1]][a] * 
                    (r[s_next[0]][s_next[1]] + gamma * 
                                 Q[s_next[0]][s_next[1]][a_next] - Q[s[0]][s[1]][a])
        #dQ = eta * (r[s_next[0]][s_next[1]] + gamma * 
                            # Q[s_next[0]][s_next[1]][a_next] - Q[s[0]][s[1]][a])

        Q[s[0]][s[1]][a] += dQ
        
        if(dQ != 0):
            number[s[0]][s[1]][a] +=1
            eta[s[0]][s[1]][a] = 1 / number[s[0]][s[1]][a]
            
        s = s_next
        a = a_next 
        
    epsilon *= epsilon_update

## The best actions

In [13]:
np.max(np.around(Q, decimals=1), axis = 2)

array([[  34.9,   38.7,   34.9,   38.7,   44.3,   38.7,   53.1,   47.8],
       [  38.7,   34.9,   38.7,   43. ,   48.6,   65.6,   59. ,   53.1],
       [  43. ,   38.3,   43. ,   47.8,   53.1,   72.9,   65.6,   59. ],
       [  47.8,   43. ,   47.8,   53.1,   59. ,   81. ,   59. ,   65.6],
       [  43. ,   53.4,   53.1,   59. ,   65.6,   90. ,   65.6,   72.9],
       [  59. ,   65.6,   59. ,   65.6,   72.9,  100. ,   72.9,   65.6],
       [  53.1,   72.9,   81. ,   90. ,  100. ,    0. ,  100. ,   90. ],
       [   0. ,   65.6,   72.9,   81. ,   90. ,  100. ,   90. ,   81. ]])

## All actions

In [14]:
np.around(Q, decimals=1)

array([[[  28.2,   34.9,    0. ,    0. ],
        [  31.4,   38.7,    0. ,    0. ],
        [  31.6,   34.9,    0. ,    0. ],
        [  31.4,   38.7,   15.7,   36.8],
        [  34.9,   44.3,   43. ,    0. ],
        [  38.7,    0. ,   38.7,   38.7],
        [  43. ,   53.1,   43. ,   47.8],
        [   0. ,   47.8,   38.7,   43. ]],

       [[  31.4,   38.7,   34.9,    0. ],
        [  34.9,    0. ,   31.4,    0. ],
        [  38.7,   38.7,   31.4,    0. ],
        [  43. ,   43. ,   28.2,   36.8],
        [  47.8,   48.6,   25.4,    0. ],
        [  53.1,   65.6,    0. ,   34.9],
        [  43. ,   59. ,    0. ,   47.8],
        [  47.8,   53.1,   53.1,   43. ]],

       [[  34.9,   43. ,   38.7,    0. ],
        [  38.3,    0. ,   34.9,    0. ],
        [  42. ,   43. ,   33.1,    0. ],
        [  45.6,   47.8,   38.7,   34. ],
        [  48.1,   53.1,   34.9,    0. ],
        [  47.8,   72.9,   59. ,    0. ],
        [  53.1,   65.6,   65.6,   53.1],
        [  53.1,   59. ,   59.